project:
  type: website
  output-dir: docs

website:
  title: "385-website"
  navbar:
    background: primary
    search: true
    left:
      - href: index.qmd
        text: Homepage
      - about.qmd
      - href: AE04-survey-types.qmd
        text: Survey Types
    right:
      - icon: github
        href: https://github.com/ninian728
  

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true

editor: visual

